pom.xml

This resolves the WELD-00018 warnings in logs (see https://issues.jboss.org/browse/FORGE-2771)

Update to Forge 3.8.1.Final

---

pom.xml
services/openshift-service-impl/src/test/java/io/fabric8/launcher/service/openshift/impl/OpenShiftServiceIT.java

fix(test): verifies that listing projects contains created one

---

openshift/template.yaml

Merge only after https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/993 is completed

Add missing OSIO entries

---

addons/launcher-addon/src/main/java/io/fabric8/launcher/addon/BoosterCatalogFactory.java
addons/launcher-addon/src/main/java/io/fabric8/launcher/addon/ui/booster/ChooseDeploymentTypeStep.java
base/src/main/java/io/fabric8/launcher/base/EnvironmentSupport.java
base/src/test/java/io/fabric8/launcher/base/EnvironmentSupportTest.java

env support for Boolean

---

addons/osio-addon/src/main/java/io/fabric8/forge/generator/EnvironmentVariables.java
addons/osio-addon/src/main/java/io/fabric8/forge/generator/keycloak/KeycloakEndpoint.java
addons/osio-addon/src/main/java/io/fabric8/forge/generator/kubernetes/KubernetesClientFactory.java
web/src/main/java/io/fabric8/launcher/web/api/OpenShiftResource.java

Wait until https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1164 is fixed

Fixes https://github.com/openshiftio/openshift.io/issues/1684: Use multi-cluster proxy

---

pom.xml

- jackson 2.9.4
- httpclient 4.5.5
- github.api 1.92
- okhttp 3.9.1
- junit system rules 1.17.1

chore(deps): updates dependencies

---

README.md
base/src/main/java/io/fabric8/launcher/base/identity/UserPasswordIdentity.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/bitbucket/impl/BitbucketServiceFactoryImpl.java

[Continue PR 96](https://github.com/fabric8-launcher/launcher-backend/pull/96)

feat(git): add git Bitbucket provider (continue because merged too soon)

---

addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/tenant/Tenant.java
addons/new-osio-addon/src/test/java/io/fabric8/launcher/osio/tenants/TenantIT.java

fix(test): Fixes TenantIT

---

addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/http/HttpExceptionMapper.java

This exception mapper converts any HttpExceptions from external services to the caller

feat(http): Introduced HttpExceptionMapper

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/bitbucket/impl/BitbucketServiceFactoryImpl.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/bitbucket/impl/BitbucketServiceImpl.java
services/git-service-impl/src/test/resources/hoverfly/bb-simulation.json

A bug as been created in KeyCloak because provided bitbucket oauth token is always expired (one hour after authorization).
https://issues.jboss.org/browse/KEYCLOAK-6774
Fixes #105

feat(bitbucket): Add TokenIdentity support

---

core/core-impl/src/test/java/io/fabric8/launcher/core/impl/MissionControlIT.java

MissionControlIT test was never deleting github repository 'foo'
Fixes #102, #112

fix(IT): MissionControlIT test was never deleting github repository

---

addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/OsioEndpoint.java
core/core-api/src/main/java/io/fabric8/launcher/core/api/security/Secured.java
core/core-impl/pom.xml
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/filters/SecuredFilter.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/filters/SecuredEndpoint.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/filters/SecuredIT.java
web/src/main/java/io/fabric8/launcher/web/endpoints/GitEndpoint.java
web/src/main/java/io/fabric8/launcher/web/endpoints/LaunchEndpoint.java

Needed for the protected endpoints in the swagger doc. Fixes https://github.com/fabric8-launcher/launcher-backend/issues/122

feat(core): Introduced @Secured

---

web/src/main/java/io/fabric8/launcher/web/producers/GitServiceProducer.java

It may introduce security issues and it complicates the flow

chore(git): Remove support for X-Git-Token

---

services/git-service-api/src/main/java/io/fabric8/launcher/service/git/api/GitUser.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/bitbucket/impl/BitbucketServiceImpl.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/github/impl/KohsukeGitHubServiceImpl.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceImpl.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/bitbucket/impl/BitbucketServiceIT.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceIT.java

feat(GIT): Remove GitUser.getEmail()

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/github/impl/KohsukeGitHubServiceImpl.java
web/src/main/java/io/fabric8/launcher/web/providers/IllegalStateExceptionMapper.java

fix(github): Better error handling for GitHub organizations

---

addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/OsioMissionControl.java
addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java

chore(osio): Fire missing events

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/GitHelper.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceImpl.java
services/git-service-impl/src/test/resources/hoverfly/gl-simulation.json

fix(GITLAB): fixed full repository name check instead of encode

---

web/src/main/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpoint.java
web/src/test/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpointIT.java

fixes https://github.com/fabric8-launcher/launcher-planning/issues/124

fix(osio) added git repo and ref

---

web/src/main/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpoint.java
web/src/test/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpointIT.java

chore(it): Fixes BoosterCatalogEndpointIT

---

cico_run_tests.sh

Fixes fabric8-launcher/launcher-planning#98

fix(test): Run integration tests during build 

---

openshift/template.yaml
web/pom.xml
web/src/main/resources/logging.properties
web/src/main/resources/modules/io/sentry/main/module.xml

feat(sentry): Enable sentry

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/jenkins/JenkinsPipeline.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/jenkins/JenkinsPipelineRegistry.java
addons/osio-addon/src/test/java/io/fabric8/launcher/osio/jenkins/JenkinsPipelineEndpointIT.java

Required for https://github.com/fabric8-launcher/launcher-planning/issues/122

feat(jenkins): Add techPreview and stage descriptions

---

addons/legacy-osio-addon/pom.xml
core/core-impl/pom.xml
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/filters/SecuredFilter.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/filters/SecuredIT.java
pom.xml

Fixes https://github.com/fabric8-launcher/launcher-planning/issues/130

feat(core): Validate JWT token structure in the header

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/GitSteps.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/bitbucket/BitbucketService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/github/KohsukeGitHubService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/gitlab/GitLabService.java

fix(OSIO): Handle launch without GitOrganization specified

---

README.md
addons/legacy-osio-addon/pom.xml
cico_build_deploy.sh
pom.xml

feat(sonar): Enable sonar during master builds

---

README.md
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/EnvironmentVariables.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/identity/OsioIdentityProvider.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/identity/OsioIdentityRequests.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/producers/OpenShiftServiceProducer.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/producers/OsioOpenShifts.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/OsioImportProjectileContext.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/OsioProjectileContext.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/tenant/TenantProducer.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/tenant/TenantRequests.java
addons/osio-addon/src/test/java/io/fabric8/launcher/osio/steps/OpenShiftStepsTest.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/MissionControlImpl.java
launcher-env-template.sh
services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/fabric8/openshift/client/Fabric8OpenShiftServiceImpl.java
services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/spi/OpenShiftServiceSpi.java
web/src/main/java/io/fabric8/launcher/web/PackageMarker.java
web/src/main/java/io/fabric8/launcher/web/endpoints/websocket/MissionControlStatusEndpoint.java
web/src/test/java/io/fabric8/launcher/web/BaseResourceIT.java
web/src/test/java/io/fabric8/launcher/web/Deployments.java
web/src/test/java/io/fabric8/launcher/web/endpoints/osio/OsioEndpointIT.java
web/src/test/java/io/fabric8/launcher/web/endpoints/osio/OsioStatusClientEndpoint.java
web/src/test/java/io/fabric8/launcher/web/endpoints/websocket/MissionControlStatusEndpointIT.java
web/src/test/java/io/fabric8/launcher/web/endpoints/websocket/StatusTestClientEndpoint.java
web/src/test/java/io/fabric8/launcher/web/endpoints/websocket/TestEventEndpoint.java
web/src/test/resources/arquillian.xml

The OsioEndpointIT covers /launch and /import osio endpoints.
This commit includes:
- a change in OsioStatusClientEndpointIT to make it client/server
- some minor delegation refactor to make osio requests
Fixes #186

test(osio): IT for OsioEndpoint

---

pom.xml
web/src/main/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpoint.java
web/src/main/webapp/swagger.yaml

Fixes https://github.com/fabric8-launcher/launcher-planning/issues/136

feat(booster-catalog): Filter by runsOn

---

web/src/main/java/io/fabric8/launcher/web/providers/CorsFilter.java

fix(cors): CORS Filter now works in Firefox

---

addons/osio-addon/pom.xml
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/preparers/CreateJenkinsfilePreparer.java
addons/osio-addon/src/test/java/io/fabric8/launcher/osio/preparers/CreateJenkinsfilePreparerTest.java
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/pipeline/inject/Jenkinsfile
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/pipeline/inject/Jenkinsfile-result
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/pipeline/inject/Jenkinsfile-result-empty
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/pipeline/multi/Jenkinsfile
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/pipeline/multi/Jenkinsfile-result
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/pipeline/no-inject/Jenkinsfile
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/test-project1/.openshiftio/Jenkinsfile.setup.snippet
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/test-project3/Jenkinsfile
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/test-project4/.openshiftio/Jenkinsfile.after.snippet
addons/osio-addon/src/test/resources/jenkinsfile-preparer-test/test-project4/.openshiftio/Jenkinsfile.setup.snippet

find `// INJECT FRAGMENT` and replaces that with found `Jenkinsfile.snippets` in `.openshiftio` folder

feature(config-map): Added way to inject jenkins file snippets

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/identity/OsioIdentityProvider.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/producers/OsioRequestScopedProducer.java
base/src/main/java/io/fabric8/launcher/base/identity/IdentityHelper.java
base/src/test/java/io/fabric8/launcher/base/identity/IdentityHelperTest.java
core/core-api/src/main/java/io/fabric8/launcher/core/spi/IdentityProvider.java
services/keycloak-service-api/src/main/java/io/fabric8/launcher/service/keycloak/api/KeycloakService.java
services/keycloak-service-impl/src/main/java/io/fabric8/launcher/service/keycloak/impl/KeycloakServiceImpl.java
web/src/main/java/io/fabric8/launcher/web/api/ValidationResource.java
web/src/main/java/io/fabric8/launcher/web/endpoints/OpenShiftEndpoint.java
web/src/main/java/io/fabric8/launcher/web/producers/GitServiceProducer.java
web/src/main/java/io/fabric8/launcher/web/producers/IdentityProviderProducer.java
web/src/main/java/io/fabric8/launcher/web/producers/MissionControlProducer.java
web/src/main/java/io/fabric8/launcher/web/producers/OpenShiftServiceProducer.java
web/src/main/java/io/fabric8/launcher/web/providers/LauncherIdentityProvider.java

and make it @RequestScoped
Fixes #230

refactor(identity): Change IdentityProvider signature

---

addons/osio-addon/pom.xml
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/OsioImportProjectileContext.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/GitHelper.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/git/GitHelperTest.java
web/src/main/java/io/fabric8/launcher/web/endpoints/inputs/LaunchProjectileInput.java

fix(endpoint): Add pattern checking to git params

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioMissionControl.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/GitSteps.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioEndpoint.java
base/src/main/java/io/fabric8/launcher/base/JsonUtils.java
base/src/main/java/io/fabric8/launcher/base/http/ExternalRequest.java
core/core-api/src/main/java/io/fabric8/launcher/core/api/Projectile.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/steps/GitSteps.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/steps/OpenShiftSteps.java
web/src/main/java/io/fabric8/launcher/web/api/MissionControlResource.java
web/src/main/java/io/fabric8/launcher/web/endpoints/LaunchEndpoint.java

Ease testing and may be a first step to support server side events in the future

refactor(core): Introduced Projectile.getEventConsumer

---

web/src/main/java/io/fabric8/launcher/web/api/OpenShiftResource.java
web/src/main/java/io/fabric8/launcher/web/endpoints/OpenShiftEndpoint.java

fix(cdi): don't use parallelStream and CDI at the same time

---

addons/legacy-osio-addon/src/main/java/io/fabric8/forge/generator/pipeline/JenkinsPipelineLibrary.java

The pull was failing so instead of spending too much time on this, we just remove the folder if it exists before cloning the repository

fix(legacy-osio): JenkinsPipelineLibrary delete dir if exists before clone

---

services/git-service-api/src/main/java/io/fabric8/launcher/service/git/api/GitOrganization.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/bitbucket/BitbucketService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/gitlab/GitLabService.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/git/AbstractGitServiceTest.java
web/src/main/java/io/fabric8/launcher/web/endpoints/GitEndpoint.java

Fixes https://github.com/fabric8-launcher/launcher-backend/issues/268

fix(git): Sort Git organizations

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubService.java
services/git-service-impl/src/test/resources/hoverfly/githubservicetest/createrepositorywithorganization.json
services/git-service-impl/src/test/resources/hoverfly/githubservicetest/getrepositories.json

fix(git): repository endpoint returns forks as well

---

CODE_OF_CONDUCT.md
COMMIT_MSG.md
CONTRIBUTING.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md
README.md

This PR includes 5 new documents:
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- COMMIT_MSG.md
- PULL_REQUEST_TEMPLATE.md
- ISSUE_TEMPLATE.md
with links in the README.md
This is a first shot and is meant to be discussed & evolve.
Closes #255

docs(community): Improves community standards

---

openshift/template.yaml

Reverts fabric8-launcher/launcher-backend#314

Revert "chore(template): Try alternative syntax"

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/OsioAuthClient.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/OsioJenkinsClient.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/OsioWitClient.java
base-test/pom.xml
base-test/src/main/java/io/fabric8/launcher/base/test/hoverfly/LauncherHoverflyRuleConfigurer.java
base/pom.xml
base/src/main/java/io/fabric8/launcher/base/http/Requests.java
base/src/test/java/io/fabric8/launcher/base/http/RequestsTest.java
base/src/test/resources/hoverfly/requeststest/shouldexecuteandfailcorrectly.json
base/src/test/resources/hoverfly/requeststest/shouldexecuteandparsejsonhandleerrorswithdetailscorrectly.json
base/src/test/resources/hoverfly/requeststest/shouldexecutecorrectly.json
base/src/test/resources/hoverfly/requeststest/shouldpostandhandleerrorscorrectly.json
base/src/test/resources/hoverfly/requeststest/shouldpostandparsecorrectly.json
base/src/test/resources/hoverfly/requeststest/shouldreadjsoncorrectly.json
base/src/test/resources/hoverfly/requeststest/shouldreturnemptywhennotfoundusingparsejsoncorrectly.json
base/src/test/resources/hoverfly/requeststest/shouldreturnemptywhenparsejsonreturnsnullcorrectly.json
base/src/test/resources/hoverfly/requeststest/shouldthrowexceptionwithdetailswhenanerroroccurs.json
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/catalog/RhoarBoosterCatalogFactory.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/bitbucket/BitbucketService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/gitlab/GitLabService.java
services/keycloak-service-impl/pom.xml
services/keycloak-service-impl/src/main/java/io/fabric8/launcher/service/keycloak/impl/KeycloakServiceImpl.java
services/keycloak-service-impl/src/test/java/io/fabric8/launcher/service/keycloak/impl/KeycloakServiceImplTest.java
services/keycloak-service-impl/src/test/resources/hoverfly/keycloakserviceimpltest/shouldgetgithubtokencorrectly.json
services/keycloak-service-impl/src/test/resources/hoverfly/keycloakserviceimpltest/shouldgetprovidertokencorrectly.json

See individual commit logs for details
Closes #247 #249 #319

Add some new hoverfly unit tests and a bit of refactor

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/catalog/RhoarBoosterCatalogFactory.java

Marking it as @Singleton won't trigger any calls to this method again.

fix: produced RhoarBoosterCatalog should be @Dependent

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/filters/SecuredFilter.java
web/src/main/java/io/fabric8/launcher/web/api/OpenShiftResource.java

fix(web): return an empty array in `/api/openshift/clusters` when no authorization provided

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java

closes: https://github.com/openshiftio/openshift.io/issues/3319

fix(osio): build not working for organization

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/GitSteps.java

fix(github): No need to check if hook exists - save an extra request

---

services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/Fabric8OpenShiftServiceImpl.java
services/openshift-service-impl/src/test/java/io/fabric8/launcher/service/openshift/impl/Fabric8OpenShiftServiceImplTest.java

feat(openshift): Add SOURCE_REPOSITORY_NAME template parameter

---

web/src/main/java/io/fabric8/launcher/web/api/OpenShiftResource.java

Reverts fabric8-launcher/launcher-backend#387

Revert "fix(osio): always use jenkins proxy"

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubService.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/git/AbstractGitServiceTest.java
services/git-service-impl/src/test/resources/hoverfly/githubservicetest/createrepositorywithorganization.json
services/git-service-impl/src/test/resources/hoverfly/githubservicetest/getrepositories.json

fix(git): GitHub impl of getRepositories should not return archived repositories

---

pom.xml
web/pom.xml

build: using RHOAR version

---

core/core-impl/src/test/java/io/fabric8/launcher/core/impl/preparers/ChangeArquillianConfigurationPreparerIT.java

test(#429): complete assertion for test and rename test

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/preparers/ChangeArquillianConfigurationPreparer.java

fix(#448): secure transformer by enabling secure-processing

---

base/src/main/java/io/fabric8/launcher/base/Paths.java
base/src/test/java/io/fabric8/launcher/base/PathsTest.java

More info: https://snyk.io/research/zip-slip-vulnerability

fix: fixed zip slip vulnerabilty

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioImportEndpoint.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioLaunchEndpoint.java
web/src/main/java/io/fabric8/launcher/web/endpoints/LaunchEndpoint.java
web/src/main/java/io/fabric8/launcher/web/endpoints/websocket/MissionControlStatusEndpoint.java
web/src/main/webapp/swagger.yaml

Fixes: https://github.com/fabric8-launcher/launcher-planning/issues/167

feat(events): return the possible events in the invoked endpoint

---

services/openshift-service-api/src/main/java/io/fabric8/launcher/service/openshift/api/OpenShiftService.java
services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/Fabric8OpenShiftServiceImpl.java
services/openshift-service-impl/src/test/java/io/fabric8/launcher/service/openshift/impl/OpenShiftServiceIT.java

fix(openshift): projectExists now uses the specific project endpoint

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioConfigs.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioLaunchMissionControl.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/AnalyticsClient.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/OsioProjectile.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/AnalyticsSteps.java
addons/osio-addon/src/test/java/io/fabric8/launcher/osio/client/AnalyticsClientTest.java
addons/osio-addon/src/test/resources/hoverfly/analyticsclienttest/should_run_depeditor_cve_analyses.json
launcher-env-template.sh
openshift/template.yaml
web/src/test/java/io/fabric8/launcher/web/endpoints/osio/OsioLaunchEndpointIT.java

Adding AnalyticsClient and AnalyticsSteps to call analytics services from the launcher backend.

feat(osio): add AnalyticsClient and AnalyticsSteps

---

web/src/main/webapp/swagger.yaml

Closes #...
- [] I followed the contribution [guidelines](https://raw.githubusercontent.com/fabric8-launcher/launcher-backend/master/CONTRIBUTING.md).
- [] I created an [issue](https://github.com/fabric8-launcher/launcher-backend/issues/new) and used it in the commit message.
- [] I have built the project locally prior to submission with `mvn clean install`.
- [] I kept a clean commit log (no unnecessary commits, no merge commits).
- [] I am happy with my contribution.

fix(swagger): Updated swagger file with `suggested` property for versions

---

addons/osio-addon/src/test/java/io/fabric8/launcher/osio/steps/OpenShiftStepsTest.java
addons/osio-addon/src/test/resources/hoverfly/openshiftsteps-simulation.json
launcher-env-template.sh

Based on https://github.com/openshiftio/openshift.io/issues/4125 Openshift Proxy has a new URL right now.

fix: proper OpenShift Proxy URL for preview environment

---

docker.sh

Removed some unused env vars and improved an error message

Just a minor fix

---

.github/PULL_REQUEST_TEMPLATE.md

Makes me wonder if anyone actually uses that template or we just select-all and delete :)

fix(gh-template): proper checklist for PR

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioImportEndpoint.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioLaunchEndpoint.java
web/src/main/java/io/fabric8/launcher/web/endpoints/LaunchEndpoint.java

Fixes https://github.com/fabric8-launcher/launcher-planning/issues/172

fix: AsyncResponse.resume is not flushed until the OutputStream is closed

---

web/src/main/java/io/fabric8/launcher/web/endpoints/GitEndpoint.java
web/src/main/java/io/fabric8/launcher/web/endpoints/models/GitDetailedUser.java
web/src/main/webapp/swagger.yaml

- This update the `/user` endpoint to add user's organizations and repositories.
- The swagger.yaml is updated.
Closes #546

fix(git): Enhance current git user endpoint to get more info in one request

---

web/src/main/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpoint.java

Required for https://github.com/fabric8-launcher/launcher-planning/issues/181

fix(booster-catalog): icon may be optional

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/filters/SecuredFilter.java

Revert this commit when token errors are sorted out (check Sentry for more information)

fix(core): Disable token validation

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/steps/OpenShiftSteps.java
services/openshift-service-api/src/main/java/io/fabric8/launcher/service/openshift/api/OpenShiftService.java
services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/Fabric8OpenShiftServiceImpl.java
services/openshift-service-impl/src/test/java/io/fabric8/launcher/service/openshift/impl/OpenShiftServiceIT.java

feat: return routes in the websocket status

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/context/OsioProjectileContext.java
core/core-api/src/main/java/io/fabric8/launcher/core/api/projectiles/context/CreateProjectileContext.java
core/core-api/src/main/java/io/fabric8/launcher/core/api/projectiles/context/IDEGenerationCapable.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/preparers/VSCodePreparer.java
core/core-impl/src/main/resources/vscode/fuse/extensions.json
core/core-impl/src/main/resources/vscode/nodejs/extensions.json
core/core-impl/src/main/resources/vscode/spring-boot/extensions.json
core/core-impl/src/main/resources/vscode/thorntail/extensions.json
core/core-impl/src/main/resources/vscode/vert.x/extensions.json
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/preparers/VSCodePreparerTest.java
web/src/main/java/io/fabric8/launcher/web/endpoints/inputs/LaunchProjectileInput.java
web/src/main/java/io/fabric8/launcher/web/endpoints/inputs/ZipProjectileInput.java

Signed-off-by: Jeff MAURY <jmaury@redhat.com>
To provide VSCode recommandations files
Will add VSCode recommandation file to the generated project in order to let user know which VSCode extensions are good for him
Closes #537.

Issue #537: Generate .vscode recommandations file

---

core/core-impl/src/main/resources/vscode/fuse/extensions.json

Signed-off-by: Aurélien Pupier <apupier@redhat.com>
Closes #...

Provide VS Code recommended extension for Camel/Fuse #632

---

services/git-service-api/src/main/java/io/fabric8/launcher/service/git/spi/GitServiceFactories.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/GitServiceFactoriesImpl.java
web/pom.xml
web/src/main/java/io/fabric8/launcher/web/producers/GitServiceProducer.java
web/src/test/java/io/fabric8/launcher/web/producers/GitServiceProducerTest.java

refactor: read X-Git-Authorization header

---

web/src/main/java/io/fabric8/launcher/web/producers/OpenShiftServiceProducer.java
web/src/main/resources/META-INF/openapi.yml
web/src/test/java/io/fabric8/launcher/web/producers/OpenShiftServiceProducerTest.java

feat(openshift): Support X-OpenShift-Authorization header

---

services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/Fabric8OpenShiftServiceImpl.java

fix(openshift): consoleUrl is not required anymore in Fabric8OpenShiftServiceImpl

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/CoreEnvironment.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/catalog/RhoarBoosterCatalogFactory.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/catalog/RhoarBoosterCatalogFactoryTest.java
core/core-impl/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
openshift/template.yaml

feat(booster-catalog): Introduced LAUNCHER_FILTER_RUNTIME and LAUNCHER_FILTER_VERSION

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/gitea/GiteaService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/gitea/GiteaServiceFactory.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/gitea/GiteaUser.java

feat(git): Add Oauth2 support for Gitea service

---

services/git-service-api/src/main/java/io/fabric8/launcher/service/git/OAuthTokenProvider.java
services/git-service-impl/pom.xml
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/OAuthTokenProviderImpl.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/GitHubServiceFactory.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/git/OAuthTokenProviderHoverflyTest.java
services/git-service-impl/src/test/resources/hoverfly/oauthtokenproviderhoverflytest/should_fetch_token.json
web/src/main/java/io/fabric8/launcher/web/endpoints/GitEndpoint.java

As the frontend can't be trusted with a secret.
Frondend shouldn't know the secret, this way the secret is never known to the frontend
but the services are still statelss
The token is fetch and encrypted, what remains to be done is adding the client_id and client_secret into the config.

fix: Move fetching the token to the backend.

---

base/pom.xml
base/src/main/java/io/fabric8/launcher/base/Paths.java
base/src/main/java/io/fabric8/launcher/base/PosixFilePermissionSupport.java
base/src/test/java/io/fabric8/launcher/base/PathsTest.java
base/src/test/java/io/fabric8/launcher/base/PosixFilePermissionSupportTest.java
pom.xml

feat: preserve file permissions in zip

---

templates/openshift/launcher-template.yaml
templates/openshift/split/launcher-routes.yaml

Fixes https://github.com/fabric8-launcher/launcher-operator/issues/24

fix(template): create secure route

---

frontend/packages/launcher-app/src/client/impl/default.launcher.client.ts
frontend/packages/launcher-app/src/client/types.ts
frontend/packages/launcher-app/src/flows/__tests__/__snapshots__/create-new-app-flow.spec.tsx.snap
frontend/packages/launcher-app/src/flows/__tests__/__snapshots__/deploy-example-app-flow.spec.tsx.snap
frontend/packages/launcher-app/src/flows/__tests__/__snapshots__/import-existing-flow.spec.tsx.snap
frontend/packages/launcher-app/src/flows/launcher-client-adapters.ts
frontend/packages/launcher-app/src/pickers/__tests__/__snapshots__/cluster-picker.spec.tsx.snap
frontend/packages/launcher-app/src/pickers/cluster-picker.tsx
web/src/main/java/io/fabric8/launcher/web/producers/OpenShiftServiceProducer.java
web/src/test/java/io/fabric8/launcher/web/producers/OpenShiftServiceProducerTest.java

@edewit let's use this branch and PR to introduce the required changes

feat(web): Support any Openshift URLs and auth. Fixes #896

---

frontend/packages/launcher-app/src/app/config.ts
frontend/packages/launcher-app/src/auth/impl/keycloak-authentication-api.ts
frontend/packages/launcher-app/src/auth/types.ts

fix: github auth link broken

---

frontend/packages/launcher-app/src/client/data-examples/mock-capabilities.json
frontend/packages/launcher-app/src/client/helpers/__snapshots__/launchers.spec.ts.snap
frontend/packages/launcher-app/src/flows/__tests__/__snapshots__/create-new-app-flow.spec.tsx.snap
frontend/packages/launcher-app/src/flows/__tests__/__snapshots__/import-existing-flow.spec.tsx.snap
frontend/packages/launcher-app/src/flows/__tests__/create-new-app-flow.spec.tsx
frontend/packages/launcher-app/src/flows/launcher-client-adapters.ts
frontend/packages/launcher-app/src/hubs/__tests__/overviews.stories.tsx
frontend/packages/launcher-app/src/loaders/__tests__/new-app-capabilities-loader.spec.tsx
frontend/packages/launcher-app/src/loaders/new-app-capabilities-loader.tsx
frontend/packages/launcher-welcome-app/src/app/capabilities/Capability.tsx
frontend/packages/launcher-welcome-app/src/app/config/capabilitiesConfig.tsx
frontend/packages/launcher-welcome-app/src/app/config/mockAppConfig.ts

fix: capabilities are prefixed with `capability-`

---

frontend/packages/launcher-welcome-app/src/app/capabilities/Capability.tsx

fix: capabilities are prefixed with `cabability-`

---

frontend/packages/launcher-app/src/flows/launcher-client-adapters.ts
frontend/packages/launcher-app/src/pickers/__tests__/__snapshots__/cluster-picker.spec.tsx.snap

fix: disable welcome app when disable by user

---

creator/src/main/resources/META-INF/catalog/runtime-angular/info.yaml
creator/src/main/resources/META-INF/catalog/runtime-react/info.yaml
creator/src/main/resources/META-INF/catalog/runtime-vuejs/info.yaml

fix(catalog): Upped memory limits for frontend runtimes

---

creator/src/main/resources/META-INF/catalog/runtime-vertx/merge-community/pom.xml
creator/src/main/resources/META-INF/catalog/runtime-vertx/merge-redhat/pom.xml

https://github.com/fabric8-launcher/launcher-application/issues/998

Update Vert.x runtime to 3.8.x

---

creator/src/main/resources/META-INF/catalog/runtime-vertx/merge-redhat/pom.xml

fix(catalog) Fixed vert.x prod version

---

creator/src/main/resources/META-INF/catalog/enums.yaml

Fix update vertx catalog

---

creator/src/main/resources/META-INF/catalog/database-crud-thorntail/files/src/main/webapp/generator-examples/database-crud-thorntail/index.html
creator/src/main/resources/META-INF/catalog/database-crud-thorntail/info.yaml
creator/src/main/resources/META-INF/catalog/enums.yaml
creator/src/main/resources/META-INF/catalog/rest-thorntail/files/src/main/webapp/generator-examples/rest-thorntail/index.html
creator/src/main/resources/META-INF/catalog/rest-thorntail/info.yaml
creator/src/main/resources/META-INF/catalog/runtime-thorntail/files/pom.xml
creator/src/main/resources/META-INF/catalog/runtime-thorntail/files/src/main/webapp/generator-examples/platform-thorntail/index.html
creator/src/main/resources/META-INF/catalog/runtime-thorntail/merge-community/pom.xml
creator/src/main/resources/META-INF/catalog/runtime-thorntail/merge-redhat/pom.xml

Move from Thorntail 2.4.0 to 2.5.0. Also add support for Thorntail community and product.
Closes #1006

feat(catalog): use Thorntail 2.5.0, community and product

---

frontend/packages/launcher-app/src/app/launcher-app.tsx
frontend/packages/launcher-app/src/auth/impl/openshift-authentication-api.ts

fix: store redirect uri for gitlab

---

frontend/packages/launcher-app/src/app/launcher-app.tsx

fix: change cancel to go to home

---

frontend/packages/launcher-app/src/auth/impl/openshift-authentication-api.spec.ts
frontend/packages/launcher-app/src/auth/impl/openshift-authentication-api.ts
frontend/packages/launcher-app/src/hubs/dest-repository-hub.tsx

fix: move link creation into try catch block

---

frontend/packages/launcher-app/public/index.html
frontend/packages/launcher-app/src/app/config.ts
frontend/packages/launcher-app/src/flows/launch-flow.tsx

fix: added support for google analytics

---

frontend/packages/launcher-app/src/hubs/welcome-app-hub.tsx

https://github.com/fabric8-launcher/launcher-application/issues/1022
Looks (to me) like a typo
Closes #...

Change a word to "prepare" (regarding #1022)

---

README.md
openshift/template.yaml

intentionally minimal commit, testing launchpad-staging saas deploy

---

frontend/packages/launcher-app/.env.production-api
frontend/packages/launcher-app/src/app/config.ts
frontend/packages/launcher-app/src/flows/create-new-app-flow.tsx
frontend/packages/launcher-app/src/flows/deploy-example-app-flow.tsx
frontend/packages/launcher-app/src/flows/launch-flow.tsx
frontend/packages/launcher-app/src/launcher/launcher.tsx
launcher-env-template.sh
openshift/template.yaml
web/src/main/resources/META-INF/settings-tmpl.json

feat: Add option to remove deploy to cluster from UI
