fabric8-launcher/launcher-application

addons/osio-addon/pom.xml
addons/osio-addon/src/main/resources/io/fabric8/forge/generator/versions/versions.properties
pom.xml
services/github-service-impl/src/main/java/io/fabric8/launcher/service/github/impl/kohsuke/KohsukeGitHubServiceImpl.java
services/github-service-impl/src/test/java/io/fabric8/launcher/service/github/impl/kohsuke/GitHubServiceIT.java
services/openshift-service-impl/src/test/java/io/fabric8/launcher/service/openshift/impl/OpenShiftServiceIT.java
web/pom.xml
web/src/test/java/io/fabric8/launcher/web/api/LaunchResourceIT.java

- Bumped most of the dependencies besides Arquillian. It seems that Shrinkwrap Resolver changed how the dependencies are fetched and with newest version (3.0.x, vs 3.0.0-alpha-4 we have here) there are classloading issues while deploying tests archives. I will open issue about it
- Improved few tests by using `assertj` and `rest-assured`
- Aligned naming for `version.` properties in poms

chore: dependency updates and tests improvements

---

services/git-service-impl/src/test/java/io/fabric8/launcher/service/github/impl/GitHubServiceIT.java

It seems that integration tests were broken. Hence I have two questions:
- why do we have them if we don't run them as a part of the build?
- shouldn't `mvn clean install` run them by default? What's the benefit of `it` profile?

fix(test): adds missing AbstractGitService

---

addons/launcher-addon/pom.xml
addons/launcher-addon/src/main/java/io/fabric8/launcher/addon/ui/booster/ChooseDeploymentTypeStep.java

`Boolean.getBoolean` only uses the `System.getProperty`, but once deployed `"LAUNCHER_SKIP_OOF_CATALOG_INDEX"` is a environment variable

can also be an env property

---

web/src/test/java/io/fabric8/launcher/web/api/HealthResourceIT.java

As we already have in-memory git server in place we can local git repositories while running tests instead of talking with github. This PR brings the use of it for `HealthResourceIT` as we are loading boosters while deploying the whole app.

fix: makes use of in-memory git server

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/github/impl/KohsukeGitHubRepositoryImpl.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/github/impl/KohsukeGitHubServiceImpl.java

Currently deleting the repository results with `java.lang.ArrayIndexOutOfBoundsException: 1`.
```
java.lang.ArrayIndexOutOfBoundsException: 1
at org.kohsuke.github.GitHub.getRepository(GitHub.java:443)
at io.fabric8.launcher.service.github.impl.KohsukeGitHubServiceImpl.deleteRepository(KohsukeGitHubServiceImpl.java:338)
at io.fabric8.launcher.service.github.impl.GitHubServiceIT.lambda$after$1(GitHubServiceIT.java:108)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.j …
```

fix: proper github delete repository call

---

pom.xml
services/git-service-impl/src/test/resources/arquillian.xml
web/src/test/java/io/fabric8/launcher/web/api/HealthResourceIT.java
web/src/test/resources/arquillian.xml

I removed the `universe` BOM for two reasons:
- when updating to latest `1.2.0.0` it was causing integration tests to fail with very strange classpath issues, similar to this one [SWARM-1759](https://issues.jboss.org/browse/SWARM-1759)
- it wasn't actually used, as we were implicitly using `arquillian-junit-container` from there, so there was no actual benefit of using BOM at all
Bonuses:
- adds `arquillian.xml` with the configuration to export deployments - useful for troubleshooting
- bumps testing libraries

chore: updates arquillian-core

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceImpl.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/github/impl/GitHubServiceIT.java

Again, integration tests were not running successfully for me after latest changes on `master`. This revealed two issues:
- GitHub accounts not always have email available publicly - thus testing, or even assuming it's always there should not take place
- GitLab API for getting created project wasn't working when using `groups`. `users` resource should be used instead. This problem in fact leads to two follow-up questions
- is our abstraction with organizations good enough? There is no notions of groups on GitHub nor organizations in GitLab and I'm not sure if we can treat them as the same concepts. Maybe the abstraction we are building is not good / needed here?
- instead of plain http calls against GitLab maybe we can consider switching to one of the Java clients …

fix(tests): integration tests fixes

---

services/git-service-impl/src/test/java/io/fabric8/launcher/service/github/impl/GitHubServiceIT.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceIT.java

- Relaxed condition as we use different accounts/organizations for actual GH calls - therefore simulation file might contain different username/repos. In addition, `GET /user` call is encrypted in the simulation file - making it harder to manipulate
- Minor improvements in the test itself:
- `assertj` assertions
- temp folder rule - proper delete even when test fails

fix: relaxes assertions for GH tests

---

services/openshift-service-impl/pom.xml
services/openshift-service-impl/src/test/java/io/fabric8/launcher/service/openshift/impl/OpenShiftClusterRegistryTest.java

Fixes #60
Findings:
In OpenShiftClusterRegistryImpl, to find [apiUrl](https://github.com/fabric8-launcher/launcher-backend/blob/master/services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/OpenShiftClusterRegistryImpl.java#L31) and [consoleUrl](https://github.com/fabric8-launcher/launcher-backend/blob/master/services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/OpenShiftClusterRegistryImpl.java#L32), current implementation is looking for system property or env variable, If we run tests using `mvn clean install`, it's setting system property for `LAUNCHER_MISSIONCONTROL_OPENSHIFT_API_URL` and `LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL` which should clear it before executing tests.

Fixes failing OpenShiftClusterRegistryTest 

---

README.md

When using 'source ...' the parameter $0 is not working.
We use $BASH_SOURCE to get the file location instead.

Fix environment script

---

addons/new-osio-addon/fetch-jenkins-pipeline.sh
addons/new-osio-addon/pom.xml
addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/jenkins/JenkinsPipeline.java
addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/jenkins/JenkinsPipelineEndpoint.java
addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/jenkins/JenkinsPipelineRegistry.java

We clone the Jenkins Pipeline Library repository and read all the available
.yaml files which we then process into a list of `JenkinsPipeline` objects.
A REST interface exists to obtain and query the list.

feat(osio): Develop /services/jenkins/pipelines (#52)

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/steps/GitSteps.java
services/git-service-api/src/main/java/io/fabric8/launcher/service/git/api/GitService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/github/impl/KohsukeGitHubServiceImpl.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceImpl.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/github/impl/GitHubServiceIT.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceIT.java
services/git-service-impl/src/test/resources/hoverfly/gh-simulation.json

Where to find those in git apis:
- config key to add secret for github "secret":
https://developer.github.com/v3/repos/hooks/#create-a-hook
- url param to add secret for gitlab "token":
https://docs.gitlab.com/ee/api/projects.html#add-project-hook
Update tests in accordance.
Fixed version of #72, closes #59

feat(git): Add possibility to use a 'secret' when creating a git hook

---

pom.xml
web/src/main/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpoint.java

Now using the booster-catalog-service version 24.
Fixes #79

feat(jenkins): Add `pipelinePlatform` to `booster-catalog/runtimes` output

---

README.md

Make documentation clearer about unsetting credentials to use KeyCloak server
It was not clear that Openshift and Git credentials needed to be unset in order to use a KeyCloak server.
Launcher environment is now displayed when sourcing the script to ensure everything is set as expected.

fix(README): Make documentation clearer about unsetting credentials

---

README.md

dirname "$BASH_SOURCE" is relative so it's always "./"

fix(README): Fix environment script directory issue

---

addons/new-osio-addon/src/test/java/io/fabric8/launcher/osio/HoverflyRuleConfigurer.java
pom.xml
services/git-service-impl/src/test/java/io/fabric8/launcher/service/github/impl/GitHubServiceIT.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/hoverfly/HoverflyRuleConfigurer.java
services/git-service-impl/src/test/resources/hoverfly/gh-simulation.json

* updated Hoverfly-java to 0.10.0
* fixed `GitHubServiceIT#throwExceptionOnDuplicateWebhook` test 
* replaced deprecated method `HoverflyConfig.configs()` with `HoverflyConfig.localConfigs()`
fixes: #92

fix(#92): updated Hoverfly to 0.10.0 & fixed test in GitHubServiceIT

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/github/impl/KohsukeGitHubServiceFactoryImpl.java

Fixes a bug which required the default Github identity to be always set

fix(github): Github token env is not mandatory

---

addons/launcher-addon/src/main/java/io/fabric8/launcher/addon/preparers/ChangeArquillianConfigurationPreparer.java
addons/launcher-addon/src/test/java/io/fabric8/launcher/addon/preparers/ChangeArquillianConfigurationPreparerTest.java
addons/launcher-addon/src/test/resources/configuration/arquillian.xml

**Why?**
Boosters have a special profile which [defines system property](https://github.com/bartoszmajsak/wfswarm-booster-pipeline-test/blob/bartoszmajsak-patch-1/pom.xml#L195) called `app.name` set for integration tests execution (`failsafe`). This is customizable, as the user can name his project anyhow he wants while using quickstart wizard.
The same property is then used as a service name when injecting [`@RouteUrl`](https://github.com/bartoszmajsak/wfswarm-booster-pipeline-test/blob/d6d7bf39a848fffc678788ba865d8471f83a0e03/src/test/java/io/openshift/booster/OpenshiftIT.java#L43) in the integration test itself. This however, does not work in Che as the property is not recognized.
By assuming boosters have `app.name` defined in arquillian.xml something like
```xml
<extension …
```

Update "app.name" property for openshift extension  defined in arquillian.xml for any booster while creating project

---

services/git-service-api/src/main/java/io/fabric8/launcher/service/git/api/GitService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/bitbucket/impl/BitbucketServiceImpl.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/github/impl/KohsukeGitHubServiceImpl.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceImpl.java
services/git-service-impl/src/test/resources/hoverfly/gl-simulation.json

GitLab is now doing the same as GitHub and Bitbucket. 
It is now looking for an owned repository when only the name is given (instead of a memberOf repository)
Fixes #101

fix(GIT): Make getRepository contract uniform across git providers

---

addons/osio-addon/src/test/java/io/fabric8/launcher/osio/steps/OpenShiftStepsTest.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/GitHubTestCredentials.java
services/git-service-api/src/main/java/io/fabric8/launcher/service/git/bitbucket/api/BitbucketEnvVarSysPropNames.java
services/git-service-api/src/main/java/io/fabric8/launcher/service/git/bitbucket/api/BitbucketWebhookEvent.java
services/git-service-api/src/main/java/io/fabric8/launcher/service/git/github/api/GitHubEnvVarSysPropNames.java
services/git-service-api/src/main/java/io/fabric8/launcher/service/git/github/api/GitHubWebhookEvent.java
services/git-service-api/src/main/java/io/fabric8/launcher/service/git/gitlab/api/GitLabEnvVarSysPropNames.java
services/git-service-api/src/main/java/io/fabric8/launcher/service/git/gitlab/api/GitLabWebhookEvent.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/bitbucket/BitbucketService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/bitbucket/BitbucketServiceFactory.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/InvalidPathException.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubRepository.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubServiceFactory.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubWebhook.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/gitlab/GitLabService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/gitlab/GitLabServiceFactory.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/git/bitbucket/BitbucketServiceIT.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/git/github/GitHubServiceFactoryTest.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/git/github/GitHubServiceIT.java
services/git-service-impl/src/test/java/io/fabric8/launcher/service/git/gitlab/GitLabServiceIT.java

For package consistency:
Move .service.github, .service.bitbucket, .. to .service.git.github, ...
In order to have service.openshift, service.git, ..., as single root packages for each services

refactor(git): Make git service package more consistent

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/OsioImportProjectileContext.java

Space path name requires validation:
- Application name must contain only letters (uppercase and lowercase), numbers, hyphens, underscores.
- It can not start and end with hyphens, spaces or underscores.
- It should be minimum 4 characters long.
- It should be maximum 63 characters long.
- It should start with a forward slash.

Adding proper validation to the space path

---

web/src/main/webapp/swagger.yaml

Managing changes in the swagger.yaml can be cumbersome. It's better to have
it stored in the launcher-backend repository and rendered externally

feat(swagger): Host the swagger.yaml in launcher-backend

---

Dockerfile.deploy
docker.sh

Using `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` to adjust
the memory heap to what's defined in the pod. The parent docker image is now using the
`fabric8/java-jboss-openjdk8-jdk` image, which calculates the container restriction.
Based on https://developers.redhat.com/blog/2017/03/14/java-inside-docker/
See https://hub.docker.com/r/fabric8/java-jboss-openjdk8-jdk/ for more details about the parent Docker image
Needed for #224

feat(memory): Change Dockerfile.deploy to use memory flags

---

web/src/main/webapp/swagger.yaml

currently for `/osio/launch`  endpoint `projectName` is missing which is required parameter. Updated swagger doc accordingly

fix(swagger): add projectName as required parameter

---

addons/launcher-addon/src/main/java/io/fabric8/launcher/addon/preparers/ChangeArquillianConfigurationPreparer.java
addons/launcher-addon/src/test/java/io/fabric8/launcher/addon/preparers/ChangeArquillianConfigurationPreparerIT.java
addons/launcher-addon/src/test/java/io/fabric8/launcher/addon/preparers/ChangeArquillianConfigurationPreparerTest.java
addons/launcher-addon/src/test/resources/configuration/arquillian-without-app-name-property.xml

*Proposed Changes*
* Add `app.name` for `openshift` extension with application `artifactId` in  `arquillian.xml` with. Previously it was updating only if `app.name` is already present.
* Fix unit test.

fix(arquillian-preparer): insert 'app.name' property if not present in openshift extension

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioMissionControl.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java

In new launcher experience jenkins config does not take git organization name only takes github user name and jenkins scan-organization scans github user space only.
fixes: #250

fix: ensure create jenkins config take github organization name if exist

---

web/src/main/java/io/fabric8/launcher/web/api/OpenShiftResource.java

`TokenIdentity` CDI proxy instance was not working in the `parallelStream()` thread. Replace instance by `ImmutableTokenIdentity.copyOf(authorizationInstance.get());`

fix(openshift): error while loading openshift cluster list

---

openshift/template.yaml

Using the `${{ }}` syntax with double braces messes with my scripts, let's see
if we can do without.

chore(template): Try alternative syntax

---

web/src/main/java/io/fabric8/launcher/web/providers/LauncherParamConverterProvider.java
web/src/main/java/io/fabric8/launcher/web/providers/MissionParamConverter.java
web/src/main/java/io/fabric8/launcher/web/providers/RuntimeParamConverter.java
web/src/test/java/io/fabric8/launcher/web/endpoints/LauncherParamConverterProviderIT.java

When any JAX-RS parameter using Mission or Runtime is used, the instances must be queried from the RhoarBoosterCatalog,
otherwise JAX-RS will construct a new object that uses the ID only.
Not using the original object will produce some unexpected results (see ReadmePreparer), where Mission.getName() returns the Mission ID.
This converter also validates if the Mission and Runtime exist in the catalog, otherwise a 400 - Bad request is thrown.

fix(converter): Mission and Runtime parameters must be provided by the RhoarBoosterCatalog

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/AbstractGitService.java

Git disallows pushing from incomplete history branches. 
Another option is using `git fetch --unshallow` but unfortunately JGit doesn't seem to support that.

fix(osio): Cannot push to cloned repositories with --depth=1

---

web/pom.xml
web/src/main/resources/modules/org/jboss/as/product/main/dir/META-INF/MANIFEST.MF
web/src/main/resources/modules/org/jboss/as/product/main/module.xml

It displays the following output:
```
2018-04-17 16:19:26,755 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0049: Fabric8 Launcher ca6ff049b269731d162b2894a85f3f27e4139c1c (WildFly Core 3.0.8.Final) starting
```
Fixes #312

chore: show project version (commit hash) when starting up.

---

services/openshift-service-api/src/main/java/io/fabric8/launcher/service/openshift/api/OpenShiftCluster.java
web/src/main/java/io/fabric8/launcher/web/endpoints/OpenShiftEndpoint.java
web/src/main/webapp/swagger.yaml

/services/openshift:
```
[
{
"cluster": {
"id": "openshift-v3",
"type": "local"
},
"connected": true
}
]
```
/services/openshift/clusters/all:
```
[
{
"id": "openshift-v3",
"type": "local"
}
]
```
Fixes #313

feat(openshift): /services/openshift now returns a richer information about the available clusters

---

web/src/main/java/io/fabric8/launcher/web/providers/gzip/GZipFilter.java
web/src/main/java/io/fabric8/launcher/web/providers/gzip/GZipServletOutputStream.java
web/src/main/java/io/fabric8/launcher/web/providers/gzip/GZipServletResponseWrapper.java

Why GZip Compress Content?
--------------------------
GZip compressing makes the data sent to the browser smaller. This speeds up the download. This is especially beneficial for mobile phones where internet bandwidth may be limited. GZip compressing content adds a CPU overhead on the server and browser, but it is still speeding up the total page load compared to not GZip compressing.
GZip HTTP Headers
-----------------
The browser includes the `Accept-Encoding` HTTP header in requests sent to an HTTP server (e.g. a Java web server). The content of the `Accept-Encoding` header tells what content encodings the browser can accept. If that header contains the value gzip in it, the browser can accept GZip compressed content. The server can then GZip compress the content sent back to the …

feat(gzip): Enable GZIP compression

---

core/core-api/src/main/java/io/fabric8/launcher/core/api/projectiles/CreateProjectile.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/MissionControlImpl.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/steps/GitSteps.java

In the new flow we can also specify which organisation we want to create the git repo
This fixes an issue
Closes could not find the issue
- [] I created an [issue](https://github.com/fabric8-launcher/launcher-backend/issues/new) and used it in the commit message.

fix(git): make sure that git organization is use when creating the git

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/catalog/RhoarBoosterCatalogFactory.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/catalog/ScriptingRhoarBoosterPredicate.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/catalog/ScriptingRhoarBoosterPredicateTest.java
openshift/template.yaml

This introduces a Predicate<RhoarBooster> implementation that can be activated by providing the `LAUNCHER_BOOSTER_CATALOG_FILTER` env param/system property.
The script must evaluate to a boolean using the `booster` variable, that is an instance of RhoarBooster.
Examples:
- `booster.mission.id == 'rest-http'`: will return only HTTP Rest mission boosters
- `booster.runtime.id == 'spring-boot'`: returns only the Spring Boot boosters
- `booster.mission.id == 'rest-http' && booster.runtime.id` == 'spring-boot': returns only HTTP Rest Spring Boot boosters
- `booster.metadata.istio`: returns only boosters that contains the `istio: true` flag in the booster metadata
- `booster.mission.metadata.istio`: returns only boosters that contains the `istio: true` flag in the mission metadata assigned to …

feat(booster-catalog): Support filtering by a script expression

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/identity/KeycloakIdentityProvider.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/identity/KeycloakIdentityProviderHoverflyTest.java
core/core-impl/src/test/resources/hoverfly/keycloakidentityproviderhoverflytest/should_get_cluster_token_correctly.json
core/core-impl/src/test/resources/hoverfly/keycloakidentityproviderhoverflytest/should_get_empty_when_cluster_is_not_connected.json
core/core-impl/src/test/resources/hoverfly/keycloakidentityproviderhoverflytest/should_get_empty_with_invalid_token.json
core/core-impl/src/test/resources/hoverfly/keycloakidentityproviderhoverflytest/should_get_github_token_correctly.json

Following previous behavior getIdentity/getIdentityAsync are supposed to catch and log exception then return empty. This was causing the error because the endpoint was failing on the first unconnected cluster.
Closes #351

fix(keycloak): handle errors in KeycloakIdentityProvider

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java

Build pipeline showing two builds
1. `applicationName` 
2. `githubUsername/organizationName.applicationName`
related issue: https://github.com/openshiftio/openshift.io/issues/3281
Closes https://github.com/openshiftio/openshift.io/issues/3281

fix(osio): bug fix for build pipeline

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/OsioIdentityProvider.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/OsioWitClient.java
addons/osio-addon/src/test/java/io/fabric8/launcher/osio/client/OsioIdentityProviderTest.java
addons/osio-addon/src/test/resources/hoverfly/osioidentityprovidertest/should_get_cluster_token_correctly.json
addons/osio-addon/src/test/resources/hoverfly/osioidentityprovidertest/should_get_empty_with_invalid_token.json
addons/osio-addon/src/test/resources/hoverfly/osioidentityprovidertest/should_get_github_token_correctly.json
base/src/main/java/io/fabric8/launcher/base/http/Requests.java
core/core-api/src/main/java/io/fabric8/launcher/core/spi/IdentityProvider.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/identity/KeycloakIdentityProviderHoverflyTest.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/Gits.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/bitbucket/BitbucketService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/gitlab/GitLabService.java

- Make OsioIdentityProvider like KeycloakIdentityProvider by always returning empty in case of error. We should change this when solving #354.
- Make OsioIdentityProvider more strict by only accepting "github" or "openshift-v3" as provider.
- Add urlEncode to Requests and use it in Osio clients.

fix(osio): make OsioIdentityProvider return empty when an error occurs

---

base/src/main/java/io/fabric8/launcher/base/identity/TokenIdentity.java

Authorizations.isBearerAuthentication already checks for null values and the test throws a better exception message.
This is	an attempt to figure out what is causing issue #351

fix: removed duplicate null check in TokenIdentity.fromBearerAuthorizationHeader

---

core/core-api/src/main/java/io/fabric8/launcher/core/api/events/StatusEventType.java

Not all builds go to Openshift Online
Removed the word "Online"

fix: remove online

---

Dockerfile.deploy.rhel
cico_build_deploy.sh

Enable build on RHEL if TARGET=rhel.
As part of an effort to migrate the services running in OSIO from CentOS
to RHEL, we are ready to push out the RHEL based image for this service
into staging.
This PR includes a new RHEL based dockerfile for the deployment of the
service.  This dockerfile will be built when this variable is set:
TARGET=rhel.  The build scripts have been adapted to take this into
consideration, and to push the image to different namespaces if the
TARGET is rhel or not.
Currently the deployment builds happen on empty baremetal machines. The
build script will be executed a second time to build and push the
deployment file if TARGET=rhel, so some changes in the build script are
to ensure that it will work if executed a second time.
By merging this PR this service will be …

Deploy on RHEL based container

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/OsioWitClient.java
addons/osio-addon/src/test/java/io/fabric8/launcher/osio/client/OsioWitClientTest.java
web/src/main/java/io/fabric8/launcher/web/endpoints/BoosterCatalogEndpoint.java
web/src/main/webapp/swagger.yaml
web/src/test/java/io/fabric8/launcher/web/endpoints/osio/OsioEndpointIT.java

The runsOn information inside the booster metadata is necessary to avoid N+1 requests

feat(booster-catalog): Return booster metadata inside /runtimes

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/preparers/ReadmePreparer.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/preparers/ReadmePreparerTest.java

Fixes https://github.com/fabric8-launcher/launcher-planning/issues/163

fix: do not overwrite README if no properties exist for target runtime

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioMissionControl.java
core/core-api/src/main/java/io/fabric8/launcher/core/api/events/StatusMessageEventBroker.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/events/StatusMessageEventBrokerImpl.java
core/core-impl/src/main/java/io/fabric8/launcher/core/impl/producers/StatusMessageEventBrokerProducer.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/events/StatusMessageEventBrokerImplTest.java
web/src/main/java/io/fabric8/launcher/web/endpoints/LaunchEndpoint.java
web/src/main/java/io/fabric8/launcher/web/endpoints/websocket/MissionControlStatusEndpoint.java
web/src/test/java/io/fabric8/launcher/web/endpoints/websocket/MissionControlStatusEndpointIT.java
web/src/test/java/io/fabric8/launcher/web/endpoints/websocket/TestEventEndpoint.java

This avoids the tight coupling of CDI when reporting messages and also allows different implementations in the future (ActiveMQ Artemis as the messaging storage for example)

feat(core): Introduced StatusMessageEventBroker

---

web/src/main/java/io/fabric8/launcher/web/endpoints/inputs/LaunchProjectileInput.java
web/src/test/java/io/fabric8/launcher/web/endpoints/inputs/LaunchProjectileInputTest.java

If project name exceeds 49 characters length then Jenkins fails to execute the job.
See https://github.com/openshiftio/openshift.io/issues/2527#issuecomment-401681596 
To fix this issue added project constraints on project name length

fixes project name length issue

---

addons/osio-addon/pom.xml
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/projectiles/context/OsioImportProjectileContext.java
addons/osio-addon/src/test/java/io/fabric8/launcher/osio/projectiles/context/OsioImportProjectileContextTest.java
pom.xml
web/src/main/java/io/fabric8/launcher/web/endpoints/inputs/LaunchProjectileInput.java
web/src/test/java/io/fabric8/launcher/web/endpoints/inputs/LaunchProjectileInputTest.java

If project name exceeds 49 characters length then Jenkins fails to execute the job.
See https://github.com/openshiftio/openshift.io/issues/2527#issuecomment-401681596 
Reverts the PR changes of https://github.com/fabric8-launcher/launcher-backend/pull/468. Updated the right class.
To fix this issue added project constraints on project name length

 fixes project name length issue

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioImportMissionControl.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioLaunchMissionControl.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioImportEndpoint.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/web/endpoints/OsioLaunchEndpoint.java

Pushing code later may trigger a build and two builds are getting triggered, so first push code
then create webhook and we are already triggering build later.
Fixes https://github.com/openshiftio/openshift.io/issues/3742
Fixes https://github.com/openshiftio/openshift.io/issues/3252
I linked the PR to OSIO issues.

Reordered the launch process, code push first then webhook creation

---

addons/osio-addon/pom.xml

This way I can source alternative pipeline repository for local testing (using `-Djenkinsfile.library.repo` while building). Small, but useful :)

feat: makes jenkinsfile-library git location configurable

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioStatusEventKind.java

OSIO is not an official name and thus should not be used in the UI
Renames the event
Closes #509

fix(#509): renames codebase event

---

base/src/main/java/io/fabric8/launcher/base/http/HttpClient.java

Not closing response on async complete might lead to resource leaks
Fixes response handling on `Async` executes.

fix: closes response on async consumption

---

core/core-api/src/main/java/io/fabric8/launcher/core/api/projectiles/context/CreateProjectileContext.java
core/core-api/src/main/java/io/fabric8/launcher/core/api/projectiles/context/LauncherProjectileContext.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/preparers/ChangeArquillianConfigurationPreparerIT.java
web/src/main/java/io/fabric8/launcher/web/endpoints/LaunchEndpoint.java
web/src/main/java/io/fabric8/launcher/web/endpoints/inputs/ZipProjectileInput.java

Fallsback to ArtifactId if projectName is not provided
Fixes https://github.com/fabric8-launcher/launcher-planning/issues/168

fix(launch): Zip file name now correctly assumes the project name

---

core/core-api/pom.xml
core/core-api/src/main/java/io/fabric8/launcher/core/spi/Application.java
core/core-api/src/test/java/io/fabric8/launcher/core/spi/ApplicationTypeConversionTest.java

We missed javadoc and tests for it in #557

chore: documents app-type extraction from header

---

openshift/template.yaml
services/git-service-api/src/main/java/io/fabric8/launcher/service/git/spi/GitProvider.java
web/src/main/java/io/fabric8/launcher/web/producers/GitServiceProducer.java

This introduces a LAUNCHER_GIT_PROVIDER environment variable to specify which Git provider to use in this backend
Fixes #566

feature(git): Support specifying the default git provider

---

core/core-impl/src/main/java/io/fabric8/launcher/core/impl/preparers/ChangeNodeJSMetadataPreparer.java
core/core-impl/src/test/java/io/fabric8/launcher/core/impl/preparers/ChangeNodeJSMetadataPreparerTest.java
core/core-impl/src/test/resources/package-result.json
core/core-impl/src/test/resources/package.json

Instead of creating a lot of if else logic on the front-end it's better just to use the project name as application name for node, as we don't need to fill out the maven artifactId
Use project name instead of artifactId in package.json
Fixes: https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/9113/

fix: use project name instead of maven artifactId

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioImportMissionControl.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioLaunchMissionControl.java

Potential fix for: openshiftio/openshift.io#3742
Unsure if this change is a good one to make as there are comments in the code which outline the order and perhaps indicate that there was an issue when the order was reversed...? Will fix the comments if this is what we agree to try!
```
// create webhook after push so that it will not trigger build
gitSteps.createWebHooks(projectile, repository);
// push code changes first so that push event will not trigger build
// and we are already trigerring build later
gitSteps.pushToGitRepository(projectile, repository);
```
Inverting order: https://github.com/fabric8-launcher/launcher-backend/pull/610#issuecomment-449319572
Closes #3742

changing order of events

---

services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubService.java
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/github/KohsukeGitHubServiceFactory.java

This should resolve sporadic 404 when looking up repositories while creating webhooks
See https://github.com/openshiftio/openshift.io/issues/4696

fix(github): Disable internal HTTP Client cache when hitting Github

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/che/CheStack.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/che/CheStackDetector.java
addons/osio-addon/src/test/java/io/fabric8/launcher/osio/che/CheStackDetectorTest.java
addons/osio-addon/src/test/resources/io/fabric8/launcher/osio/che/golang/main.go
addons/osio-addon/src/test/resources/io/fabric8/launcher/osio/che/nodejs/package.json

The Golang stack was missing. The Golang boosters cannot run with node/java che stacks.
This PR 
- Adds new Golang enum to CheStacks
- Updates CheStackDetector to check for golang stack

Chore: Add Golang stack

---

core/core-impl/src/main/resources/vscode/fuse/extensions.json

it is reducing the number of "recommended" extension that the user will
see and then will reduce the number of click that he/she will need to do
to install the recommended extension to work on the project
Camel Extension Pack have these dependencies:
https://github.com/camel-tooling/vscode-camel-extension-pack/blob/bbea1b162fa9c341a670d5c6aec9e6962ee3720a/package.json#L20-L25
Camel Extension pack have dependencies on the Java Extension pack which contains the following extensions:
https://github.com/Microsoft/vscode-java-pack/blob/b7d845d2ff783f3cc95c70573c7d0674f50f1bb8/package.json#L83-L88
Closes #649

Use top-level recommended extension pack for Camel #649

---

addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioImportMissionControl.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/OsioLaunchMissionControl.java
addons/osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java
services/openshift-service-api/src/main/java/io/fabric8/launcher/service/openshift/api/OpenShiftService.java
services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/Fabric8OpenShiftServiceImpl.java
web/src/test/java/io/fabric8/launcher/web/endpoints/osio/OsioImportEndpointIT.java
web/src/test/java/io/fabric8/launcher/web/endpoints/osio/OsioLaunchEndpointIT.java
web/src/test/java/io/fabric8/launcher/web/endpoints/osio/OsioStatusClientEndpoint.java

When a new project is created, two builds are triggered (not always because of a race condition). See openshiftio/openshift.io#3742
1. Because of webhook. We setup webhook before initial commit and that triggers one build (This build doesn't always work because **there is race condition between the config map and the webhook event** @hrishin found this out.)
2. Because of manual trigger build. (this build always work)
In 3001505 we removed the manual build trigger and as a result we had openshiftio/openshift.io#4752 . openshiftio/openshift.io#4752 shows that we have a race condition between the first webhook event and the config map that stores the Jenkins config.
This PR changes the sequence of events so that **we ALWAYS get ONE build**.
The new sequence looks like
1. Create Repository …

Trigger build before adding webhook

---

pom.xml
services/git-service-impl/pom.xml
services/git-service-impl/src/main/java/io/fabric8/launcher/service/git/AbstractGitService.java

Failsafe is a lightweight, zero-dependency library for handling failures in Java 8+, with a concise API for handling everyday use cases and the flexibility to handle everything else.
It works by wrapping executable logic with one or more resilience policies, which can be combined and composed as needed.
https://github.com/jhalterman/failsafe

feat(git): Using Failsafe library for retrying operations

---

web/src/main/java/io/fabric8/launcher/web/endpoints/OpenShiftEndpoint.java

@gastaldi I improved things in Quarkus but the root of the issue was this missing status, which brought a loooot of unwanted classes as we were trying to mark everything accessible to the Resource class.
Quarkus PR to follow to fix the remaining things.

Make ClusterVerified inner class static

---

services/openshift-service-api/src/main/java/io/fabric8/launcher/service/openshift/api/OpenShiftService.java
services/openshift-service-api/src/main/java/io/fabric8/launcher/service/openshift/api/OpenShiftUser.java
services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/Fabric8OpenShiftServiceImpl.java
web/src/main/java/io/fabric8/launcher/web/endpoints/OpenShiftEndpoint.java
web/src/main/resources/META-INF/openapi.yml

Returns the user name logged in OpenShift, like:
{
"name": "app-launcher"
}
Fixes #696

feat(openshift): Introduce /services/openshift/user

---

web/src/main/java/io/fabric8/launcher/web/endpoints/OpenShiftEndpoint.java

fixing: https://github.com/fabric8-launcher/launcher-frontend/issues/1004, https://github.com/fabric8-launcher/launcher-frontend/issues/999
Instead of letting the front-end do n calls ( where n is the number of connected clusters ) to verify if the token stored in keycloak is still valid. We can make the clusters call more "robust" by checking the tokens inline.

fix: made cluster connected more robust by also checking if the token in keycloak is valid.

---

services/openshift-service-impl/src/main/java/io/fabric8/launcher/service/openshift/impl/OpenShiftClusterRegistryImpl.java

Right now not setting a cluster file result in an error
but since we now allow the user to specify a custom cluster
we should allow not having any clusters defined. It also
makes testing easier when you don't need to configure
everything.

feat(openshift): Allow not setting a cluster file

---

pom.xml

Fixes CVE-2019-12402 
The file name encoding algorithm used internally in Apache Commons Compress 1.15 to 1.18 can get into an infinite loop when faced with specially crafted inputs. This can lead to a denial of service attack if an attacker can choose the file names inside of an archive created by Compress.

bump commons-compress to 1.19
